### ISSUE TITLE
Missing docker image in Docker Hub for tag node12-jdk8-6.2.2.36-1

### ISSUE THREAD

**Issue by ruester** [terrestris/gitlab-runner-image#3]
Would it be possible to push the docker image from the tag [node12-jdk8-6.2.2.36-1](https://github.com/terrestris/gitlab-runner-image/tree/node12-jdk8-6.2.2.36-1) also to Docker Hub? It seems to be missing there or some Docker Hub policies already deleted the image again...

**Comment by hwbllmnn** [comment]
I built and pushed it again.
